//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SilverlightWCF_RIA.Web
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class StudentsEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“StudentsEntities”部分中的连接字符串初始化新 StudentsEntities 对象。
        /// </summary>
        public StudentsEntities() : base("name=StudentsEntities", "StudentsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 StudentsEntities 对象。
        /// </summary>
        public StudentsEntities(string connectionString) : base(connectionString, "StudentsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 StudentsEntities 对象。
        /// </summary>
        public StudentsEntities(EntityConnection connection) : base(connection, "StudentsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<student> student
        {
            get
            {
                if ((_student == null))
                {
                    _student = base.CreateObjectSet<student>("student");
                }
                return _student;
            }
        }
        private ObjectSet<student> _student;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 student EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTostudent(student student)
        {
            base.AddObject("student", student);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StudentsModel", Name="student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class student : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 student 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static student Createstudent(global::System.Int32 id)
        {
            student student = new student();
            student.id = id;
            return student;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String xingming
        {
            get
            {
                return _xingming;
            }
            set
            {
                OnxingmingChanging(value);
                ReportPropertyChanging("xingming");
                _xingming = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("xingming");
                OnxingmingChanged();
            }
        }
        private global::System.String _xingming;
        partial void OnxingmingChanging(global::System.String value);
        partial void OnxingmingChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String xingbie
        {
            get
            {
                return _xingbie;
            }
            set
            {
                OnxingbieChanging(value);
                ReportPropertyChanging("xingbie");
                _xingbie = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("xingbie");
                OnxingbieChanged();
            }
        }
        private global::System.String _xingbie;
        partial void OnxingbieChanging(global::System.String value);
        partial void OnxingbieChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String jiguan
        {
            get
            {
                return _jiguan;
            }
            set
            {
                OnjiguanChanging(value);
                ReportPropertyChanging("jiguan");
                _jiguan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("jiguan");
                OnjiguanChanged();
            }
        }
        private global::System.String _jiguan;
        partial void OnjiguanChanging(global::System.String value);
        partial void OnjiguanChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zhuanye
        {
            get
            {
                return _zhuanye;
            }
            set
            {
                OnzhuanyeChanging(value);
                ReportPropertyChanging("zhuanye");
                _zhuanye = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("zhuanye");
                OnzhuanyeChanged();
            }
        }
        private global::System.String _zhuanye;
        partial void OnzhuanyeChanging(global::System.String value);
        partial void OnzhuanyeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> kaofen
        {
            get
            {
                return _kaofen;
            }
            set
            {
                OnkaofenChanging(value);
                ReportPropertyChanging("kaofen");
                _kaofen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kaofen");
                OnkaofenChanged();
            }
        }
        private Nullable<global::System.Double> _kaofen;
        partial void OnkaofenChanging(Nullable<global::System.Double> value);
        partial void OnkaofenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dianhua
        {
            get
            {
                return _dianhua;
            }
            set
            {
                OndianhuaChanging(value);
                ReportPropertyChanging("dianhua");
                _dianhua = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dianhua");
                OndianhuaChanged();
            }
        }
        private global::System.String _dianhua;
        partial void OndianhuaChanging(global::System.String value);
        partial void OndianhuaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] zhaopian
        {
            get
            {
                return StructuralObject.GetValidValue(_zhaopian);
            }
            set
            {
                OnzhaopianChanging(value);
                ReportPropertyChanging("zhaopian");
                _zhaopian = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("zhaopian");
                OnzhaopianChanged();
            }
        }
        private global::System.Byte[] _zhaopian;
        partial void OnzhaopianChanging(global::System.Byte[] value);
        partial void OnzhaopianChanged();

        #endregion
    
    }

    #endregion
    
}
